# For production
baseurl      = "https://standingpadanimations.github.io/"

# For local development
#baseurl      = "localhost"
title        = "StandingPad's Corner"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10
publishDir   = "docs"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"
  enableThemeToggle = true 

  # Subtitle for home
  homeSubtitle = "Where I post stuff, I guess"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "My corner of the internet where I post about Blender I guess. Oh and I also program virtual machines cause why not"
  keywords = "homepage, blog"
  images = [""]

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "StandingPad's Corner"
    subtitle = "The corner of the internet where I post stuff"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "StandingPad's Corner"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"
  
  [[menu.main]]
    identifier = "source"
    name       = "Website Source"
    url        = "https://github.com/StandingPadAnimations/StandingPadAnimations.github.io"

  [[menu.main]]
    identifier = "about"
    name       = "About Me"
    url        = "/about"

[[params.social]]
  name = "mastodon"
  url = "https://social.vivaldi.net/@StandingPad"

[[params.social]]
  name = "instagram"
  url = "https://www.instagram.com/standingpad/"

[[params.social]]
  name = "github"
  url = "https://github.com/StandingPadAnimations"

[[params.social]]
  name = "youtube"
  url = "https://www.youtube.com/@standingpad"

[[params.social]]
  name = "email"
  url = "mahidsheikh@pm.me"

